Repository openshift/cloud-ingress-operator, pull requests merged in 2020-03, with the labels that each got.

#4 Add APIScheme CRD and controller
  .gitignore
  build/Dockerfile
  cmd/manager/main.go
  deploy/crds/cloudingress.managed.openshift.io_apischemes_crd.yaml
  deploy/crds/cloudingress.managed.openshift.io_v1alpha1_apischeme_cr.yaml
  deploy/crds/cloudingress.managed.openshift.io_v1alpha1_publishingstrategy_cr.yaml
  deploy/namespace.yaml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  go.mod
  go.sum
  pkg/apis/cloudingress/v1alpha1/apischeme_types.go
  pkg/apis/cloudingress/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/cloudingress/v1alpha1/zz_generated.openapi.go
  pkg/awsclient/client.go
  pkg/awsclient/ec2_helper.go
  pkg/awsclient/elb_helper.go
  pkg/awsclient/route53_helper.go
  pkg/controller/apischeme/apischeme_controller.go
  pkg/controller/publishingstrategy/publishingstrategy_controller.go
  pkg/controller/utils/clusterinfo.go
  pkg/controller/utils/conditions.go
  project.mk
Labels: lgtm, size/XXL

#6 Add machine controller to watch Machine objects for
  cmd/manager/main.go
  pkg/controller/add_machine.go
  pkg/controller/machine/machine_controller.go
Labels: lgtm, size/L

#7 Make server API public
  deploy/cloud-ingress-operator-credentials.yml
  go.sum
  pkg/awsclient/client.go
  pkg/awsclient/elb_helper.go
  pkg/controller/apischeme/apischeme_controller.go
  pkg/controller/publishingstrategy/publishingstrategy_controller.go
  pkg/controller/utils/clusterinfo.go
Labels: lgtm, size/L

#9 Revert "Make server API public"
  deploy/cloud-ingress-operator-credentials.yml
  go.sum
  pkg/awsclient/client.go
  pkg/awsclient/elb_helper.go
  pkg/controller/apischeme/apischeme_controller.go
  pkg/controller/publishingstrategy/publishingstrategy_controller.go
  pkg/controller/utils/clusterinfo.go
Labels: size/L

#12 Return err instead of nil in 4 functions when error is thrown
  pkg/controller/utils/clusterinfo.go
Labels: lgtm, size/XS

#11 Add cicd things
  Makefile
  OWNERS
  build/Dockerfile
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
  hack/app_sre_build_deploy.sh
  hack/app_sre_create_image_catalog.sh
  hack/app_sre_pr_check.sh
  hack/generate-operator-bundle.py
  hack/generate_template.py
  hack/olm-registry/olm-artifacts-template.yaml
  hack/templates/selectorsyncset.yaml
  hack/templates/template.yaml
  hack/validate_yaml.py
  project.mk
  standard.mk
Labels: lgtm, size/XL

#14 Fix make target for app-sre app_sre_build_deploy.sh
  hack/app_sre_build_deploy.sh
Labels: size/XS

#16 Fix build/test in CI
  build/Dockerfile
  standard.mk
Labels: lgtm, size/S

#18 Added stuff to create the catalogsource (bundle)
  Makefile
  build/Dockerfile.catalog_registry
  functions.mk
  hack/app_sre_create_image_catalog.sh
  hack/generate-operator-bundle.py
  hack/templates/csv.yaml
  hack/templates/package.yaml
  project.mk
  standard.mk
Labels: lgtm, size/L

#19 Moving to one-line make for build and deploy operator and catalog images
  hack/app_sre_build_deploy.sh
  hack/app_sre_create_image_catalog.sh
Labels: lgtm, size/M

#20 Update template to deploy operator.
  Makefile
  deploy/00_openshift-cloud-ingress-operator.Namespace.yaml
  deploy/05_cloud-ingress-operator.ServiceAccount.yaml
  deploy/10_cloud-ingress-operator-credentials.CredentialsRequest.yaml
  deploy/20_cloud-ingress-operator.ClusterRole.yaml
  deploy/25_cloud-ingress-operator.ClusterRoleBinding.yaml
  deploy/30_cloud-ingress-operator-RoleBinding.yaml
  deploy/50_cloud-ingress-operator.Deployment.yaml
  deploy/90_rh-api.APIScheme.yaml
  hack/app_sre_pr_check.sh
  hack/olm-registry/olm-artifacts-template.yaml
  hack/templates/template.yaml
  standard.mk
Labels: approved, lgtm, size/L

#23 Add new ALLOWED_CIDR_BLOCKS_? params to template
  hack/olm-registry/olm-artifacts-template.yaml
  hack/templates/template.yaml
Labels: approved, lgtm

#22 Add logic to add/remove LBs from masters' ProviderSpecs
  deploy/20_cloud-ingress-operator.ClusterRole.yaml
  pkg/controller/publishingstrategy/publishingstrategy_controller.go
  pkg/controller/utils/clusterinfo.go
Labels: approved, lgtm

#24 Fixing duplicate SSS
  deploy/60_cloud-ingress-operator-registry.CatalogSource.yaml
  deploy/70_cloud-ingress-operator.Subscription.yaml
  hack/olm-registry/olm-artifacts-template.yaml
  hack/templates/template.yaml
Labels: approved, lgtm

#25 Moved example CRs to `examples/` dir
  examples/cloudingress.managed.openshift.io_v1alpha1_apischeme_cr.yaml
  examples/cloudingress.managed.openshift.io_v1alpha1_publishingstrategy_cr.yaml
  hack/olm-registry/olm-artifacts-template.yaml
Labels: approved, lgtm

#15 Logic for handling data ingresses
  cmd/manager/main.go
  deploy/20_cloud-ingress-operator.ClusterRole.yaml
  pkg/controller/publishingstrategy/publishingstrategy_controller.go
Labels: approved, lgtm, size/L

#26 Add OperatorGroup
  deploy/65_cloud-ingress-operator.OperatorGroup.yaml
  hack/olm-registry/olm-artifacts-template.yaml
Labels: approved, lgtm

#28 added the rh-api apischeme to the openshift-cloud-ingress-operator namespace
  deploy/90_rh-api.APIScheme.yaml
  hack/olm-registry/olm-artifacts-template.yaml
Labels: approved, lgtm

#29 Make routeSelector field optional
  deploy/crds/cloudingress.managed.openshift.io_publishingstrategies_crd.yaml
  pkg/apis/cloudingress/v1alpha1/publishingstrategy_types.go
  pkg/apis/cloudingress/v1alpha1/zz_generated.openapi.go
  pkg/controller/publishingstrategy/publishingstrategy_controller.go
Labels: approved, lgtm

#31 Fix logic for list of ingresscontroller to create
  pkg/controller/publishingstrategy/publishingstrategy_controller.go
Labels: approved, lgtm

#32 Refactor ingresscontroller logic from main reconcile function
  pkg/controller/publishingstrategy/publishingstrategy_controller.go
Labels: approved, lgtm

#35 Remove machine controller
  pkg/controller/add_machine.go
  pkg/controller/machine/machine_controller.go
Labels: approved, lgtm

#27 Add machine_helper.go to utils package
  go.mod
  go.sum
  pkg/controller/publishingstrategy/publishingstrategy_controller.go
  pkg/controller/utils/machine_helper.go
Labels: approved, lgtm

#34 Remove errant go-logr import and references
  pkg/controller/apischeme/apischeme_controller.go
Labels: approved, lgtm

#38 Use 'Sync' instead of 'sync' for resourceApplyMode
  Makefile
  hack/olm-registry/olm-artifacts-template.yaml
  hack/templates/selectorsyncset.yaml
Labels: approved, lgtm

#39 Update OWNERS
  OWNERS
Labels: approved, lgtm

#40 changed the CIDR_BLOCKS to be a list
  deploy/90_rh-api.APIScheme.yaml
  hack/olm-registry/olm-artifacts-template.yaml
  hack/templates/template.yaml
Labels: approved, lgtm

#41 cleaned up the template to use ${{ }} for non string option
  deploy/90_rh-api.APIScheme.yaml
  hack/olm-registry/olm-artifacts-template.yaml
Labels: approved, lgtm

#42 OSD-3127: Fix AWS admin api SecurityGroup Reconciling
  pkg/awsclient/ec2_helper.go
Labels: approved, lgtm

#43 Clean up the 'sleeping x second' messages
  pkg/controller/publishingstrategy/publishingstrategy_controller.go
Labels: approved, lgtm
