Repository openshift/cloud-ingress-operator, pull requests merged in 2020-04, with the labels that each got.

#47 Only deploy to AWS clusters
  hack/olm-registry/olm-artifacts-template.yaml
  hack/templates/selectorsyncset.yaml
Labels: approved, lgtm

#44 OSD-3162: First README.md draft
  README.md
Labels: approved, lgtm

#45 Unit tests for ingresscontroller logic
  pkg/controller/publishingstrategy/publishingstrategy_controller.go
  pkg/controller/publishingstrategy/publishingstrategy_controller_test.go
Labels: approved, lgtm

#46 OSD-3189: First tests for APIScheme controller
  go.mod
  go.sum
  pkg/awsclient/client.go
  pkg/awsclient/mock/mock_client.go
  pkg/controller/apischeme/apischeme_controller.go
  pkg/controller/apischeme/apischeme_controller_test.go
Labels: approved, lgtm

#49 Add manual testing of ingresscontroller instructions
  README.md
Labels: approved, lgtm

#50 OSD-3190: Add unit tests for utils
  pkg/controller/apischeme/apischeme_controller_test.go
  pkg/controller/utils/clusterinfo.go
  pkg/controller/utils/clusterinfo_test.go
  pkg/controller/utils/machine_helper_test.go
  pkg/testutils/testutils.go
Labels: approved, do-not-merge/hold

#54 OSD-3391, BZ 1814332: Handle missing infra PlatformStatus
  deploy/20_cluster_config_v1_reader_role.yaml
  deploy/20_cluster_config_v1_reader_role_binding.yaml
  go.mod
  go.sum
  hack/olm-registry/olm-artifacts-template.yaml
  pkg/controller/utils/clusterinfo.go
  pkg/controller/utils/clusterinfo_test.go
  pkg/testutils/testutils.go
Labels: approved, kind/bug, lgtm

#51 Match LB short name for removal
  pkg/controller/publishingstrategy/publishingstrategy_controller.go
  pkg/controller/utils/machine_helper.go
Labels: approved, lgtm

#55 Fix case where loadbalancer listening is nil
  pkg/controller/publishingstrategy/publishingstrategy_controller.go
  pkg/controller/publishingstrategy/publishingstrategy_controller_test.go
Labels: approved, kind/bug, lgtm

#56 Support deletion of non-default ingresscontroller and fix publishingStrategy logs
  examples/cloudingress.managed.openshift.io_v1alpha1_publishingstrategy_cr.yaml
  go.sum
  pkg/controller/publishingstrategy/publishingstrategy_controller.go
Labels: approved, lgtm

#58 Expose metrics endpoint for prometheus scraping
  cmd/manager/main.go
  deploy/00_openshift-cloud-ingress-operator.Namespace.yaml
  deploy/40_prom-k8s-role.yaml
  deploy/40_prom-k8s-rolebinding.yaml
  go.mod
  go.sum
  hack/olm-registry/olm-artifacts-template.yaml
  pkg/localmetrics/localmetrics.go
Labels: approved, lgtm

#53 Add tags for external NLB
  go.sum
  pkg/awsclient/client.go
  pkg/awsclient/elb_helper.go
  pkg/controller/publishingstrategy/publishingstrategy_controller.go
Labels: approved, lgtm

#57 Refactor deletion of ingress logic and add unit test
  pkg/controller/publishingstrategy/publishingstrategy_controller.go
  pkg/controller/publishingstrategy/publishingstrategy_controller_test.go
Labels: approved, lgtm
